### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by Huanle** [orangeSi/bam2msa#1]
Hi @orangeSi ,
thanks for developing this useful tool.
I ran into an error shown below when trying it out.
Can you help me sort it out?

Thanks a lot.

```
$ ./src/bam2msa -h
Unhandled exception: Index out of bounds (IndexError)
  from /usr/share/crystal/src/gc/boehm.cr:110:5 in 'parse_and_run'
  from /mnt/bam2msa.cr:487:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main'
  from ???
  from ???
```

**Comment by orangeSi** [comment]
```src/bam2msa --help``` or ```src/bam2msa``` both will output the help~
